name: Google Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake . -DBOOST_ROOT=$BOOST_ROOT_1_72_0 -DBoost_DIR=$BOOST_ROOT_1_72_0
    - name: build
      run: make
    - name: run tests
      run: ./tests

