name: Google Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Workaround for https://github.com/actions/virtual-environments/issues/10
    - name: Avoid to use GitHub Actions-installed boost
      shell: bash
      run: |
        echo "::set-env name=BOOST_ROOT::"
    - name: configure
      run: cmake . -DBOOST_ROOT=$BOOST_ROOT_1_72_0
    - name: build
      run: make
    - name: run tests
      run: ./tests

