name: Google Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: ls -l $BOOST_ROOT_1_72_0/lib/; ls -l /usr/local/share/cmake-3.17/Modules; cmake . -DBOOST_ROOT=$BOOST_ROOT_1_72_0
    - name: build
      run: make
    - name: run tests
      run: ./tests

